title: Chiranjeevi B S
logo: assets/images/CBS.png
description: Welcome to my portfolio website
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
